#!/bin/bash

#kill $(xprop -name "Eww - quicksettings" _NET_WM_PID | tail -c+24)

FIRST_MONITOR_WIDTH=1980
CURRENT_MOUSE_POSX=$(xdotool getmouselocation | grep -oP "x:\\d+" | tr -d 'x:')

if [[ "$(~/eww-source/target/release/eww active-windows)" == *"dashboard"* ]]; then
  ~/eww-source/target/release/eww close dashboard
  echo "Closing"
else
  if [[ "$CURRENT_MOUSE_POSX" -gt $FIRST_MONITOR_WIDTH ]]; then
    ~/eww-source/target/release/eww open --toggle dashboard --screen "HDMI-1" &
    disown
  else
    ~/eww-source/target/release/eww open --toggle dashboard --screen "eDP-1" &
    disown
  fi
  echo "Opening"
fi
