#!/bin/sh

workspaces_two_monitors() {
  # check if Occupied
  o1=$(bspc query -D -d .occupied --names | grep 1)
  o2=$(bspc query -D -d .occupied --names | grep 2)
  o3=$(bspc query -D -d .occupied --names | grep 3)
  o4=$(bspc query -D -d .occupied --names | grep 4)
  o5=$(bspc query -D -d .occupied --names | grep 5)
  o6=$(bspc query -D -d .occupied --names | grep 6)
  o7=$(bspc query -D -d .occupied --names | grep 7)
  o8=$(bspc query -D -d .occupied --names | grep 8)

  # check if Focused
  f1=$(bspc query -D -d focused --names | grep 1)
  f2=$(bspc query -D -d focused --names | grep 2)
  f3=$(bspc query -D -d focused --names | grep 3)
  f4=$(bspc query -D -d focused --names | grep 4)
  f5=$(bspc query -D -d focused --names | grep 5)
  f6=$(bspc query -D -d focused --names | grep 6)
  f7=$(bspc query -D -d focused --names | grep 7)
  f8=$(bspc query -D -d focused --names | grep 8)

  # le spagetti
  content1="spi"
  content2="spi"
  content3="spi"
  content4="spi"
  content5="spi"
  content6="spi"
  content7="spi"
  content8="spi"

  [[ "$f1" ]] && content1=""
  [[ "$f2" ]] && content2=""
  [[ "$f3" ]] && content3=""
  [[ "$f4" ]] && content4=""
  [[ "$f5" ]] && content5=""
  [[ "$f6" ]] && content6=""
  [[ "$f7" ]] && content7=""
  [[ "$f8" ]] && content8=""

  classworkspace1="ws"
  classworkspace2="ws"
  classworkspace3="ws"
  classworkspace4="ws"
  classworkspace5="ws"
  classworkspace6="ws"
  classworkspace7="ws"
  classworkspace8="ws"

  [[ "$o1" ]] && classworkspace1="wso"
  [[ "$o2" ]] && classworkspace2="wso"
  [[ "$o3" ]] && classworkspace3="wso"
  [[ "$o4" ]] && classworkspace4="wso"
  [[ "$o5" ]] && classworkspace5="wso"
  [[ "$o6" ]] && classworkspace6="wso"
  [[ "$o7" ]] && classworkspace7="wso"
  [[ "$o8" ]] && classworkspace8="wso"

  [[ "$f1" ]] && classworkspace1="wsf"
  [[ "$f2" ]] && classworkspace2="wsf"
  [[ "$f3" ]] && classworkspace3="wsf"
  [[ "$f4" ]] && classworkspace4="wsf"
  [[ "$f5" ]] && classworkspace5="wsf"
  [[ "$f6" ]] && classworkspace6="wsf"
  [[ "$f7" ]] && classworkspace7="wsf"
  [[ "$f8" ]] && classworkspace8="wsf"

  echo "(eventbox (box	:class \"wsbox\" :orientation \"v\"	:halign \"center\"	:valign \"start\"	 :space-evenly \"false\" :spacing \"-5\" (button :onclick \"bspc desktop -f 1\"	:class	\"$classworkspace1\"	\"$content1\") (button :onclick \"bspc desktop -f 2\"	:class \"$classworkspace2\"	 \"$content2\") (button :onclick \"bspc desktop -f 3\"	:class \"$classworkspace3\" \"$content3\") (button :onclick \"bspc desktop -f 4\"	:class \"$classworkspace4\"	\"$content4\") (button :onclick \"bspc desktop -f 5\"	:class \"$classworkspace5\" \"$content5\" ) (button :onclick \"bspc desktop -f 6\"	:class \"$classworkspace6\" \"$content6\" ) (button :onclick \"bspc desktop -f 7\"	:class \"$classworkspace7\" \"$content7\" ) (button :onclick \"bspc desktop -f 8\"	:class \"$classworkspace8\" \"$content8\" )))"
}

workspaces_one_monitor() {
  # check if Occupied
  o1=$(bspc query -D -d .occupied --names | grep 1)
  o2=$(bspc query -D -d .occupied --names | grep 2)
  o3=$(bspc query -D -d .occupied --names | grep 3)
  o4=$(bspc query -D -d .occupied --names | grep 4)
  o5=$(bspc query -D -d .occupied --names | grep 5)

  # check if Focused
  f1=$(bspc query -D -d focused --names | grep 1)
  f2=$(bspc query -D -d focused --names | grep 2)
  f3=$(bspc query -D -d focused --names | grep 3)
  f4=$(bspc query -D -d focused --names | grep 4)
  f5=$(bspc query -D -d focused --names | grep 5)

  # le spagetti
  content1="spi"
  content2="spi"
  content3="spi"
  content4="spi"
  content5="spi"

  [[ "$f1" ]] && content1=""
  [[ "$f2" ]] && content2=""
  [[ "$f3" ]] && content3=""
  [[ "$f4" ]] && content4=""
  [[ "$f5" ]] && content5=""

  classworkspace1="ws"
  classworkspace2="ws"
  classworkspace3="ws"
  classworkspace4="ws"
  classworkspace5="ws"

  [[ "$o1" ]] && classworkspace1="wso"
  [[ "$o2" ]] && classworkspace2="wso"
  [[ "$o3" ]] && classworkspace3="wso"
  [[ "$o4" ]] && classworkspace4="wso"
  [[ "$o5" ]] && classworkspace5="wso"

  [[ "$f1" ]] && classworkspace1="wsf"
  [[ "$f2" ]] && classworkspace2="wsf"
  [[ "$f3" ]] && classworkspace3="wsf"
  [[ "$f4" ]] && classworkspace4="wsf"
  [[ "$f5" ]] && classworkspace5="wsf"

  echo "(eventbox (box	:class \"wsbox\" :orientation \"v\"	:halign \"center\"	:valign \"start\"	 :space-evenly \"false\" :spacing \"-5\" (button :onclick \"bspc desktop -f 1\"	:class	\"$classworkspace1\"	\"$content1\") (button :onclick \"bspc desktop -f 2\"	:class \"$classworkspace2\"	 \"$content2\") (button :onclick \"bspc desktop -f 3\"	:class \"$classworkspace3\" \"$content3\") (button :onclick \"bspc desktop -f 4\"	:class \"$classworkspace4\"	\"$content4\") (button :onclick \"bspc desktop -f 5\"	:class \"$classworkspace5\" \"$content5\" )))"
}

if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
  workspaces_two_monitors
  bspc subscribe desktop node_transfer | while read -r _; do
    workspaces_two_monitors
  done
else
  workspaces_one_monitor
  bspc subscribe desktop node_transfer | while read -r _; do
    workspaces_one_monitor
  done
fi
