#!/bin/bash

if [[ $(pidof mocp) ]]; then
  SONG_COVER="/home/catdealer/.config/eww/fibreglass/assets/empty_music_cover.png"

  SONG_TITLE=$(mocp --format=%song)
  if [[ "$SONG_TITLE" == "" ]]; then
    SONG_TITLE="Unknown Song"
  fi

  SONG_ARTIST=$(mocp --format=%artist)
  if [[ "$SONG_ARTIST" == "" ]]; then
    SONG_ARTIST="Unknown artist"
  fi

  if [[ $(mocp --info | grep "PLAY") ]]; then
    SONG_STATUS="Playing"
  elif [[ $(mocp --info | grep "PAUSE") ]]; then
    SONG_STATUS="Paused"
  fi

  if [[ "$SONG_STATUS" == "Playing" ]]; then
    PLAY_BUTTON="/home/catdealer/.config/eww/fibreglass/assets/pause.png"
  elif [[ "$SONG_STATUS" == "Paused" ]]; then
    PLAY_BUTTON="/home/catdealer/.config/eww/fibreglass/assets/play.png"
  fi
  
  PLAYINGVIA="mocp"

else
  if [[ $(playerctl status 2>/dev/null) ]]; then
    SONG_COVER=$(playerctl metadata | grep "artUrl" | tail -c+42)
    SONG_TITLE=$(playerctl metadata | grep "title" | tail -c+35)
    SONG_ARTIST=$(playerctl metadata | grep "artist" | tail -c+35)
    SONG_STATUS=$(playerctl status)
    PLAYINGVIA=$(playerctl -l | head -1)

    if [[ "$SONG_STATUS" == "Playing" ]]; then
      PLAY_BUTTON="/home/catdealer/.config/eww/fibreglass/assets/pause.png"
    elif [[ "$SONG_STATUS" == "Paused" ]]; then
      PLAY_BUTTON="/home/catdealer/.config/eww/fibreglass/assets/play.png"
    fi
  else
    SONG_COVER="/home/catdealer/.config/eww/fibreglass/assets/empty_music_cover.png"
    SONG_TITLE="No media playing"
    SONG_ARTIST="No media playing"
    SONG_STATUS="off"
    PLAY_BUTTON="/home/catdealer/.config/eww/fibreglass/assets/play.png"
  fi
fi

toggle() {
  if [[ $(pidof mocp) ]]; then
    mocp -G
  else
    playerctl play-pause
  fi
}

next_func() {
  if [[ $(pgrep mocp) ]]; then
    mocp -f
  else
    playerctl next
  fi
}

previous_func() {
  if [[ $(pgrep mocp) ]]; then
    mocp -r
  else
    playerctl previous
  fi
}

case $1 in
--cover) echo "$SONG_COVER" ;;
--title) echo "$SONG_TITLE" ;;
--artist) echo "$SONG_ARTIST" ;;
--status) echo "$SONG_STATUS" ;;
--playingvia) echo "$PLAYINGVIA" ;;
--playing-icon) echo "$PLAY_BUTTON" ;;
--toggle) toggle ;;
--next) next_func ;;
--back) previous_func ;;
esac
