#!/bin/bash

median=$(date '+%p')
hour=$(date '+%I')

if [[ $median = "PM" ]]; then
        if [[ $hour > "06" ]]; then
		if [[ $hour = "12" ]]; then
	                echo Good Afternoon
		else
			echo Good Evening
		fi
        else
                echo Good Afternoon
        fi
else
        echo Good Morning
fi
