#!/bin/bash

if [[ $(pidof mocp) ]]; then
  SONG_COVER=""

  SONG_TITLE=$(mocp --format=%song)
  if [[ "$SONG_TITLE" == "" ]]; then
    SONG_TITLE="Unknown Song"
  fi

  SONG_ARTIST=$(mocp --format=%artist)
  if [[ "$SONG_ARTIST" == "" ]]; then
    SONG_ARTIST="Unknown artist"
  fi

  if [[ $(mocp --info | grep "PLAY") ]]; then
    SONG_STATUS="Playing"
  elif [[ $(mocp --info | grep "PAUSE") ]]; then
    SONG_STATUS="Paused"
  fi

  if [[ "$SONG_STATUS" == "Playing" ]]; then
    PLAY_BUTTON=""
  elif [[ "$SONG_STATUS" == "Paused" ]]; then
    PLAY_BUTTON=""
  fi
else
  if [[ $(playerctl status 2>/dev/null) ]]; then
    SONG_COVER=$(playerctl metadata | grep "artUrl" | tail -c+42)
    SONG_TITLE=$(playerctl metadata | grep "title" | tail -c+35)
    SONG_ARTIST=$(playerctl metadata | grep "artist" | tail -c+35)
    SONG_STATUS=$(playerctl status)

    if [[ "$SONG_STATUS" == "Playing" ]]; then
      PLAY_BUTTON=""
    elif [[ "$SONG_STATUS" == "Paused" ]]; then
      PLAY_BUTTON=""
    fi
  else
    SONG_COVER=""
    SONG_TITLE="No music playing"
    SONG_ARTIST=""
    SONG_STATUS="off"
    PLAY_BUTTON=""
  fi
fi

toggle() {
  if [[ $(pidof mocp) ]]; then
    mocp -G
  else
    playerctl play-pause
  fi
}

case $1 in
--cover) echo "$SONG_COVER" ;;
--title) echo "$SONG_TITLE" ;;
--artist) echo "$SONG_ARTIST" ;;
--status) echo "$SONG_STATUS" ;;
--playing-icon) echo "$PLAY_BUTTON" ;;
--toggle) toggle ;;
esac
